constants = {
    "test_dictionary_path": "test_dictionary.txt",
    "test_double_dictionary_path": "test_double_dictionary.txt",
    "test_matrix_path": "incident_matrix.json",
    "test_dir_path": "test_files",
    "test_result_dir_path": "test_result_files",
    "test_index_path": "test_index.txt",
    "test_double_index_path": "test_double_index.txt",
    "test_coordinate_index_path": "test_coordinate_index.json",
    "test_gramm_index_path": "test_gramm_index.txt",
    "test_shift_index_path": "test_shift_index.txt",
    "dictionary_path": "dictionary.txt",
    "double_dictionary_path": "double_dictionary.txt",
    "matrix_path": "incident_matrix.json",
    "dir_path": "files",
    "result_dir_path": "result_files",
    "index_path": "index.txt",
    "double_index_path": "double_index.txt",
    "coordinate_index_path": "coordinate_index.txt",
    "gramm_index_path": "gramm_index.txt",
    "shift_index_path": "shift_index.txt",
    "regex_splitter": "[^0-9a-zA-Z \n\n]+",
    "regex_for_index_of_verse": "[0-9]*:[0-9]*(:?)",
    "input_search_text": "Search for a word with operators AND,OR ...\n",
    "input_rebuild_index_text": "Should I re-build index file? \nIf yes - 'y', else press enter...\n",
}

